import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

export type LanguageId = 'en' | 'hi' | 'mr';

interface LanguageContextType {
    language: LanguageId;
    setLanguage: (lang: LanguageId) => Promise<void>;
    t: (key: string) => string;
}

const LANGUAGES = {
    en: {
        // Auth
        welcome_roadmap: 'Your Career Roadmap',
        auth_subtitle: 'Discover paths that match your passion.',
        sign_in: 'Sign In',
        sign_up: 'Sign Up',
        guest: 'Continue as Guest',
        email: 'Email address',
        password: 'Password',

        // Onboarding
        welcome: 'Welcome to',
        onboarding_subtitle: "Let's find the best path for your future",
        select_lang: 'Select your language',
        get_started: 'Get Started',
        choose_lang: 'Choose Language',

        // Tabs Layout
        tab_home: 'Home',
        tab_explore: 'Explore',
        tab_plan: 'My Plan',
        tab_freelance: 'Freelancing',
        tab_profile: 'Profile',

        // Home Screen
        hello_student: 'Hello, Student! 👋',
        home_subtitle: "Let's chart your career roadmap",
        explore_section: 'What would you like to explore?',
        further_edu: 'Further Education',
        further_edu_desc: 'Streams, degrees, colleges',
        start_working: 'Start Working',
        start_working_desc: 'Govt & private jobs',
        skill_courses: 'Skill Courses',
        skill_courses_desc: 'Certifications, vocations',
        start_business: 'Start a Business',
        start_business_desc: 'Ideas & freelance',
        recommended: 'Recommended for You',
        see_more: 'See More',

        // Explore Screen
        explore_title: 'College Explorer',
        explore_subtitle: 'Find the best institution for your degree',
        search_placeholder: 'Search colleges, degrees...',
        filter_all: 'All',
        filter_govt: 'Govt',
        filter_private: 'Private',
        tuition_fees: 'Tuition Fees',
        college_type: 'Type',
        placement: 'Placement',
        save: 'Save',
        view_details: 'View Details',

        // Plan Screen
        plan_title: 'My Career Plan',
        plan_subtitle: 'Track your goals and saved action items',
        status_in_progress: 'In Progress',
        status_pending: 'Pending',
        status_completed: 'Completed',
        bookmarks_title: 'Saved Bookmarks',
        no_bookmarks: 'No bookmarks yet. Explore and save colleges or courses.',

        // Assist Screen
        assist_title: 'Career Assistant',
        ask_anything: 'Ask me anything...',
        bot_initial_msg: 'Hi! I am your Career Assistant. How can I help you today?',
        bot_feedback_msg: 'That sounds like a great path! Would you like me to find some relevant courses and colleges for that area?',

        // Profile Screen
        profile_name: 'Student User',
        profile_sub: '12th Pass • Science Stream',
        retake_assessment: 'Retake Assessment',
        edit_info: 'Edit Personal Info',
        app_settings: 'App Settings',
        privacy_terms: 'Privacy & Terms',
        contact_support: 'Contact Support',
        log_out: 'Log Out',
        logout_confirm: 'Are you sure you want to log out?',
        retake_confirm: 'This will restart your career assessment. Continue?',
        cancel: 'Cancel',
        continue: 'Continue',

        // Scholarship Card
        scholarship_title: 'Scholarship of the Week 🎯',
        scholarship_name: 'State Merit Scholarship',
        scholarship_desc: 'For 12th pass students scoring 80%+',
        scholarship_grant: 'Up to ₹25,000 grant',
        scholarship_deadline: 'Apply before: March 15',
        apply_now: 'Apply Now',

        // Resume Card
        resume_instant_title: 'Create Your Resume Instantly 🧾',
        resume_instant_desc: 'Just answer 5 questions and get a PDF resume! Perfect for internships & entry-level jobs.',
        build_resume: 'Build Resume',

        // Freelancing Hub
        freelance_hub: 'Freelancing Hub',
        freelance_sub: 'Find projects or showcase your skills',
        browse_posts: 'Browse Posts',
        create_post_tab: 'Create Post',
        edit_post_tab: 'Edit Post',
        role_label: 'What is your professional role?',
        role_placeholder: 'e.g. Graphic Designer, Freelance Writer',
        desc_label: 'Tell us about your services & experience',
        desc_placeholder: 'Describe what you can do for clients...',
        skills_label: 'Skills (Comma separated)',
        skills_placeholder: 'e.g. Logo Design, Photoshop, Copywriting',
        mobile_label: 'Mobile Number *',
        mobile_placeholder: 'e.g. 9876543210',
        linkedin_label: 'LinkedIn Profile URL',
        linkedin_placeholder: 'https://linkedin.com/in/yourname',
        publish_post: 'Publish Post',
        update_post: 'Update Post',
        cancel_edit: 'Cancel Editing',
        call_now: 'Call Now',
        delete_post_title: 'Delete Post',
        delete_post_confirm: 'Are you sure you want to delete this post?',
        post_success: 'Your post has been published!',
        update_success: 'Post updated successfully!',
        no_posts: 'No posts yet. Be the first to post!',

        // Resume Builder
        resume_builder_title: 'Resume Builder',
        personal_info: 'Personal Information',
        edu_info: 'Education',
        exp_info: 'Experience / Projects',
        skills_info: 'Skills',
        full_name_ph: 'Full Name',
        email_ph: 'Email Address',
        phone_ph: 'Phone Number',
        location_ph: 'Location (City, State)',
        summary_ph: 'Professional Summary',
        add_skill: 'Add Skill',
        skill_name_ph: 'Skill name',
        add_edu: 'Add Education',
        edu_count: 'Education #',
        school_ph: 'School/College Name',
        degree_ph: 'Degree/Course (e.g. B.Tech Computer Science)',
        year_ph: 'Year (e.g. 2020 - 2024)',
        add_exp: 'Add Experience',
        item_count: 'Item #',
        company_ph: 'Company/Project Name',
        role_ph: 'Role (e.g. Software Engineer Intern)',
        duration_ph: 'Duration (e.g. June 2023 - Present)',
        desc_ph: 'Description (Optional)',
        select_tpl_preview: 'Choose Template & Preview',
        generate_pdf: 'Generate PDF',
        edit_tab: 'Edit',
        templates_tab: 'Templates',
        preview_tab: 'Preview',

        // Profile Extended
        profile_overview: 'Overview',
        profile_interests: 'Interests',
        profile_settings: 'Settings',
        edit_profile_title: 'Edit Profile',
        not_set: 'Not set',
        marks_label: 'Marks: ',
        marks_not_set: 'Marks not specified',
        no_interests: 'No interests selected',
        full_name_label: 'Full Name',
        location_label: 'Location',
        qual_label: 'Qualification',
        stream_label: 'Stream',
        marks_cgpa_label: 'Marks / CGPA',
        saving: 'Saving...',
        save_changes: 'Save Changes',
        profile_update_success: 'Profile updated successfully.',

        // Explore Extended
        after_label: 'After ',
        select_qual: 'Select Your Qualification',
        select_qual_desc: 'To show you the most relevant educational pathways',
        options_suffix: ' Options',
        goal_label: 'What is your goal?',
        no_options: 'No options found for this filter.',
        duration_label: 'Duration:',
        eligibility_label: 'Eligibility:',
        govt_jobs_label: '🏛️ Govt Jobs / Options:',
        private_sector_label: '💼 Private Sector Roles:',
        higher_study_label: '🎓 Higher Study Paths:',
        branches_coming_soon: 'Detailed branches for this pathway are coming soon!',
        coming_soon_title: 'Coming Soon',

        // Scholarship Screen Extended
        scholarships_header: 'Scholarships',
        available_count: ' scholarships available',
        search_scholarships_ph: 'Search scholarships, tags, type...',
        filter_title: 'Filter Scholarships',
        edu_level_label: 'Education Level',
        scholarship_type_label: 'Scholarship Type',
        special_cat_label: 'Special Category',
        reset_btn: 'Reset',
        apply_filters_btn: 'Apply Filters',
        found_count: ' scholarships found',
        clear_filters: 'Clear Filters',
        no_scholarships_found: 'No scholarships found',
        try_adjust_filters: 'Try adjusting your search or filters',
        load_more: 'Load More',
        end_list: "You've reached the end of the list",
        benefit_label: 'Amount / Benefit',
        eligibility_criteria: 'Eligibility Criteria',
        qual_label_small: 'Qualification',
        min_percentage_label: 'Min. Percentage',
        family_income_label: 'Family Income Limit',
        category_label_small: 'Category',
        gender_label_small: 'Gender',
        state_conditions_label: 'State Conditions',
        req_docs: 'Required Documents',
        how_to_apply: 'How to Apply (Step-by-Step)',
        renewal_cond: 'Renewal Conditions',
        apply_portal_btn: 'Apply Now / Open Portal',

        // Start Working Tab Extended
        choose_category: 'Choose a Category',
        find_jobs_matching: 'Find jobs matching your qualification & interests',
        match_score_active: 'Smart Match Score Active',
        match_score_desc: 'Jobs are ranked based on your qualification and profile.',
        jobs_count_suffix: ' Jobs',
        no_jobs_match: 'No jobs match this filter.',
        eligibility_detail_label: 'Eligibility',
        required_skills_label: 'Required Skills',
        where_to_apply_label: 'Where to Apply',
        monthly_salary_label: 'Monthly Salary',
        exam_based_label: 'Exam-Based',
        match_label: 'Match',
        apply_now_btn: 'Apply Now',

        // Skill Courses Tab Extended
        choose_skill_area: 'Choose a Skill Area',
        short_term_courses_desc: 'Short-term courses • Certifications • Job-ready skills',
        recommended_for: 'Recommended for ',
        courses_count_suffix: ' Courses',
        no_courses_match: 'No courses match this filter.',
        free_govt_training: 'Free Govt Training',
        paid_private_training: 'Paid Private Training',
        course_info_label: 'Course Info',
        duration_label_small: 'Duration',
        authority_label: 'Authority',
        mode_label: 'Mode',
        top_platforms_label: 'Top Platforms / Institutes',
        job_roles_label: 'Job Roles',

        // Business Tab Extended
        explore_business_categories: 'Explore Business Categories',
        find_perfect_business_desc: 'Find the perfect business idea for your skills & budget',
        why_start_business: 'Why start a business?',
        starting_small_business_desc: 'Starting a small business offers financial independence, flexibility, and unlimited growth potential.',
        business_ideas_count_suffix: ' Ideas',
        no_ideas_found: 'No ideas found for this category yet.',
        avg_profit_label: 'Avg. Profit: ',
        expected_profit_label: 'Expected Profit',
        time_to_break_even: 'Time to Break Even',
        financial_breakdown: 'Financial Breakdown',
        initial_setup_budget: 'Initial Setup Budget: ',
        monthly_operating_cost: 'Monthly Operating Cost:',
        req_eligibility_label: 'Requirements & Eligibility',
        manpower_needs_label: 'Manpower Needs:',
        marketing_scalability_label: 'Marketing & Scalability',
        marketing_tips_label: 'Marketing Tips:',
        scalability_potential_label: 'Scalability Potential:',
        bonus_tips_resources: 'Bonus Tips & Resources',

        // Qualification Titles
        qual_10th: '10th',
        qual_12th: '12th',
        qual_diploma: 'Diploma',
        qual_iti: 'ITI',
        qual_grad: 'Graduation',

        // New / Missing Strings
        leaving_careerpath: 'Leaving CareerPath',
        leaving_careerpath_desc: 'You are about to open an external site. Continue?',
        cannot_open_link: 'Cannot Open Link',
        link_unavailable: 'Link Unavailable',
        link_unavailable_desc: 'No official link is available or the link appears invalid.',
        unable_to_open: 'Unable to open link.',
        monthly_salary_suffix: '/mo',
        for_you_badge: '✦ For You',
        free_tag: 'FREE',
        online_mode: 'Online',
        offline_mode: 'Offline',
        blended_mode: 'Blended',
        nsdc_pmkvy_desc: 'NSDC / PMKVY / DDU-GKY',
        placement_support: 'Placement Support',
        cert_on_completion: 'Certificate on Completion',
        rural_friendly_centres: 'Rural-Friendly Centres',
        industry_recognized_certs: 'Industry-recognized certs',
        live_projects_mentors: 'Live projects & mentors',
        higher_job_roi: 'Higher job ROI',
        global_platforms: 'Global platforms',
        budget_very_low: 'Very Low',
        budget_low: 'Low',
        budget_medium: 'Medium',
        budget_high: 'High',
        example_success_tip: 'Example / Success Tip:',
        starter_kit_rec: 'Starter Kit Recommendation:',
        
        // Course Badges
        high_salary: 'High Salary',
        remote_friendly: 'Remote Friendly',
        future_skill: 'Future Skill',
        global_certification: 'Global Certification',
        govt_sponsored: 'Govt Sponsored',
        free_course: 'Free Course',
        self_employment: 'Self-Employment',
        industry_skill: 'Industry Skill',
        field_job: 'Field Job',
        freelancing_badge: 'Freelancing',
        stable_career: 'Stable Career',
        corporate_jobs: 'Corporate Jobs',
        rural_support: 'Rural Support',
        work_from_home: 'Work From Home',
        no_degree_required: 'No Degree Required',

        // Alerts & Common
        error: 'Error',
        success: 'Success',
        update_failed: 'Update Failed',
        something_went_wrong: 'Something went wrong while updating.',
        unable_find_session: 'Unable to find user session.',
        fill_mandatory_fields: 'Please fill mandatory fields (Role, Description, Mobile)',
        failed_save_post: 'Failed to save post',
        delete_btn: 'Delete',
        
        // Explore Filters & Subtitles
        filter_higher: 'Higher Study',
        filter_salary: 'High Salary',
        filter_skill: 'Skill-Based',
        filter_abroad: 'Study Abroad',
        filter_entry: 'Entry-Level',
        qual_subtitle_10th: 'Stream choice, diploma, ITI',
        qual_subtitle_12th: 'Degree, engineering, medical',
        qual_subtitle_diploma: 'B.Tech entry, govt jobs',
        qual_subtitle_iti: 'Technical roles, apprenticeships',
        qual_subtitle_grad: 'PG, UPSC, MBA, specialized jobs',

        // Explore Tags
        tag_govt_job: 'Govt Job',
        tag_private_job: 'Private Job',
        tag_high_salary: 'High Salary',
        tag_higher_study: 'Higher Study',
        tag_study_abroad: 'Study Abroad',
        tag_skill_based: 'Skill-Based',
        tag_entrepreneurship: 'Entrepreneurship',
    },
    hi: {
        // Auth
        welcome_roadmap: 'आपका करियर रोडमैप',
        auth_subtitle: 'उन रास्तों की खोज करें जो आपके जुनून से मेल खाते हों।',
        sign_in: 'साइन इन करें',
        sign_up: 'साइन अप करें',
        guest: 'अतिथि के रूप में जारी रखें',
        email: 'ईमेल पता',
        password: 'पासवर्ड',

        // Onboarding
        welcome: 'स्वागत है',
        onboarding_subtitle: 'आइए आपके भविष्य के लिए सबसे अच्छा रास्ता खोजें',
        select_lang: 'अपनी भाषा चुनें',
        get_started: 'शुरू करें',
        choose_lang: 'भाषा चुनें',

        // Tabs Layout
        tab_home: 'होम',
        tab_explore: 'एक्सप्लोर',
        tab_plan: 'मेरा प्लान',
        tab_freelance: 'फ्रीलांसिंग',
        tab_profile: 'प्रोफाइल',

        // Home Screen
        hello_student: 'नमस्ते, छात्र! 👋',
        home_subtitle: 'आइए आपका करियर रोडमैप तैयार करें',
        explore_section: 'आप क्या एक्सप्लोर करना चाहेंगे?',
        further_edu: 'आगे की शिक्षा',
        further_edu_desc: 'स्ट्रीम, डिग्री, कॉलेज',
        start_working: 'काम करना शुरू करें',
        start_working_desc: 'सरकारी और निजी नौकरियां',
        skill_courses: 'कौशल पाठ्यक्रम',
        skill_courses_desc: 'प्रमाणन, व्यवसाय',
        start_business: 'व्यवसाय शुरू करें',
        start_business_desc: 'विचार और फ्रीलांस',
        recommended: 'आपके लिए अनुशंसित',
        see_more: 'और देखें',

        // Explore Screen
        explore_title: 'कॉलेज एक्सप्लोरर',
        explore_subtitle: 'अपनी डिग्री के लिए सबसे अच्छा संस्थान खोजें',
        search_placeholder: 'कॉलेज, डिग्री खोजें...',
        filter_all: 'सभी',
        filter_govt: 'सरकारी',
        filter_private: 'प्राइवेट',
        tuition_fees: 'शिक्षण शुल्क',
        college_type: 'प्रकार',
        placement: 'प्लेसमेंट',
        save: 'सेव',
        view_details: 'विवरण देखें',

        // Plan Screen
        plan_title: 'मेरा करियर प्लान',
        plan_subtitle: 'अपने लक्ष्यों और सेव की गई वस्तुओं को ट्रैक करें',
        status_in_progress: 'प्रगति में',
        status_pending: 'लंबित',
        status_completed: 'पूरा हुआ',
        bookmarks_title: 'सेव किए गए बुकमार्क',
        no_bookmarks: 'अभी तक कोई बुकमार्क नहीं है। कॉलेज या कोर्स एक्सप्लोर करें और सेव करें।',

        // Assist Screen
        assist_title: 'करियल सहायक',
        ask_anything: 'मुझसे कुछ भी पूछें...',
        bot_initial_msg: 'नमस्ते! मैं आपका करियर सहायक हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?',
        bot_feedback_msg: 'यह एक बेहतरीन रास्ता लगता है! क्या आप चाहेंगे कि मैं उस क्षेत्र के लिए कुछ प्रासंगिक कोर्स और कॉलेज ढूंढूं?',

        // Profile Screen
        profile_name: 'छात्र यूजर',
        profile_sub: '12वीं पास • विज्ञान स्ट्रीम',
        retake_assessment: 'मूल्यांकन दोबारा करें',
        edit_info: 'व्यक्तिगत जानकारी संपादित करें',
        app_settings: 'ऐप सेटिंग्स',
        privacy_terms: 'गोपनीयता और शर्तें',
        contact_support: 'सहायता से संपर्क करें',
        log_out: 'लॉग आउट',
        logout_confirm: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
        retake_confirm: 'इससे आपका करियर मूल्यांकन दोबारा शुरू हो जाएगा। जारी रखें?',
        cancel: 'रद्द करें',
        continue: 'जारी रखें',

        // Scholarship Card
        scholarship_title: 'सप्ताह की छात्रवृत्ति 🎯',
        scholarship_name: 'राज्य मेरिट छात्रवृत्ति',
        scholarship_desc: '80%+ अंक प्राप्त करने वाले 12वीं पास छात्रों के लिए',
        scholarship_grant: '₹25,000 तक का अनुदान',
        scholarship_deadline: 'आवेदन की अंतिम तिथि: 15 मार्च',
        apply_now: 'अभी आवेदन करें',

        // Resume Card
        resume_instant_title: 'तुरंत अपना रिज्यूमे बनाएं 🧾',
        resume_instant_desc: 'बस 5 सवालों के जवाब दें और पीडीएफ रिज्यूमे पाएं! इंटर्नशिप और एंट्री-लेवल नौकरियों के लिए बिल्कुल सही।',
        build_resume: 'रिज्यूमे बनाएं',

        // Freelancing Hub
        freelance_hub: 'फ्रीलांसिंग हब',
        freelance_sub: 'प्रोजेक्ट खोजें या अपना कौशल दिखाएं',
        browse_posts: 'पोस्ट ब्राउज़ करें',
        create_post_tab: 'पोस्ट बनाएं',
        edit_post_tab: 'पोस्ट संपादित करें',
        role_label: 'आपकी पेशेवर भूमिका क्या है?',
        role_placeholder: 'जैसे ग्राफिक डिजाइनर, फ्रीलांस राइटर',
        desc_label: 'हमें अपनी सेवाओं और अनुभव के बारे में बताएं',
        desc_placeholder: 'वर्णन करें कि आप ग्राहकों के लिए क्या कर सकते हैं...',
        skills_label: 'कौशल (कौमा से अलग करें)',
        skills_placeholder: 'जैसे लोगो डिजाइन, फोटोशॉप, कॉपीराइटिंग',
        mobile_label: 'मोबाइल नंबर *',
        mobile_placeholder: 'जैसे 9876543210',
        linkedin_label: 'लिंक्डइन प्रोफाइल यूआरएल',
        linkedin_placeholder: 'https://linkedin.com/in/yourname',
        publish_post: 'पोस्ट प्रकाशित करें',
        update_post: 'पोस्ट अपडेट करें',
        cancel_edit: 'एडिटिंग रद्द करें',
        call_now: 'अभी कॉल करें',
        delete_post_title: 'पोस्ट हटाएं',
        delete_post_confirm: 'क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?',
        post_success: 'आपकी पोस्ट प्रकाशित हो गई है!',
        update_success: 'पोस्ट सफलतापूर्वक अपडेट हो गई!',
        no_posts: 'अभी तक कोई पोस्ट नहीं है। पहली पोस्ट करने वाले बनें!',

        // Resume Builder
        resume_builder_title: 'रिज्यूमे बिल्डर',
        personal_info: 'व्यक्तिगत जानकारी',
        edu_info: 'शिक्षा',
        exp_info: 'अनुभव / प्रोजेक्ट्स',
        skills_info: 'कौशल',
        full_name_ph: 'पूरा नाम',
        email_ph: 'ईमेल पता',
        phone_ph: 'फोन नंबर',
        location_ph: 'स्थान (शहर, राज्य)',
        summary_ph: 'पेशेवर सारांश',
        add_skill: 'कौशल जोड़ें',
        skill_name_ph: 'कौशल का नाम',
        add_edu: 'शिक्षा जोड़ें',
        edu_count: 'शिक्षा #',
        school_ph: 'स्कूल/कॉलेज का नाम',
        degree_ph: 'डिग्री/कोर्स (जैसे बी.टेक कंप्यूटर साइंस)',
        year_ph: 'वर्ष (जैसे 2020 - 2024)',
        add_exp: 'अनुभव जोड़ें',
        item_count: 'आइटम #',
        company_ph: 'कंपनी/प्रोजेक्ट का नाम',
        role_ph: 'भूमिका (जैसे सॉफ्टवेयर इंजीनियर इंटर्न)',
        duration_ph: 'अवधि (जैसे जून 2023 - वर्तमान)',
        desc_ph: 'विवरण (वैकल्पिक)',
        select_tpl_preview: 'टेम्पलेट चुनें और प्रीव्यू करें',
        generate_pdf: 'पीडीएफ बनाएं',
        edit_tab: 'संपादित करें',
        templates_tab: 'टेम्पलेट्स',
        preview_tab: 'प्रीव्यू',

        // Profile Extended
        profile_overview: 'अवलोकन',
        profile_interests: 'रुचियां',
        profile_settings: 'सेटिंग्स',
        edit_profile_title: 'प्रोफाइल संपादित करें',
        not_set: 'सेट नहीं है',
        marks_label: 'अंक: ',
        marks_not_set: 'अंक निर्दिष्ट नहीं हैं',
        no_interests: 'कोई रुचि नहीं चुनी गई',
        full_name_label: 'पूरा नाम',
        location_label: 'स्थान',
        qual_label: 'योग्यता',
        stream_label: 'स्ट्रीम',
        marks_cgpa_label: 'अंक / CGPA',
        saving: 'सहेज रहा है...',
        save_changes: 'परिवर्तन सहेजें',
        profile_update_success: 'प्रोफाइल सफलतापूर्वक अपडेट हो गई।',

        // Explore Extended
        after_label: 'के बाद ',
        select_qual: 'अपनी योग्यता चुनें',
        select_qual_desc: 'आपको सबसे प्रासंगिक शैक्षिक रास्ते दिखाने के लिए',
        options_suffix: ' विकल्प',
        goal_label: 'आपका लक्ष्य क्या है?',
        no_options: 'इस फ़िल्टर के लिए कोई विकल्प नहीं मिला।',
        duration_label: 'अवधि:',
        eligibility_label: 'पात्रता:',
        govt_jobs_label: '🏛️ सरकारी नौकरियां / विकल्प:',
        private_sector_label: '💼 निजी क्षेत्र की भूमिकाएं:',
        higher_study_label: '🎓 उच्च अध्ययन के रास्ते:',
        branches_coming_soon: 'इस मार्ग के लिए विस्तृत शाखाएं जल्द ही आ रही हैं!',
        coming_soon_title: 'जल्द आ रहा है',

        // Scholarship Screen Extended
        scholarships_header: 'छात्रवृत्तियां',
        available_count: ' छात्रवृत्तियां उपलब्ध हैं',
        search_scholarships_ph: 'छात्रवृत्तियां, टैग, प्रकार खोजें...',
        filter_title: 'छात्रवृत्ति फ़िल्टर करें',
        edu_level_label: 'शिक्षा का स्तर',
        scholarship_type_label: 'छात्रवृत्ति का प्रकार',
        special_cat_label: 'विशेष श्रेणी',
        reset_btn: 'रीसेट करें',
        apply_filters_btn: 'फ़िल्टर लागू करें',
        found_count: ' छात्रवृत्तियां मिलीं',
        clear_filters: 'फ़िल्टर हटाएं',
        no_scholarships_found: 'कोई छात्रवृत्ति नहीं मिली',
        try_adjust_filters: 'अपनी खोज या फ़िल्टर बदलने का प्रयास करें',
        load_more: 'और दिखाएं',
        end_list: 'आप सूची के अंत तक पहुँच गए हैं',
        benefit_label: 'राशि / लाभ',
        eligibility_criteria: 'पात्रता मानदंड',
        qual_label_small: 'योग्यता',
        min_percentage_label: 'न्यूनतम प्रतिशत',
        family_income_label: 'पारिवारिक आय सीमा',
        category_label_small: 'श्रेणी',
        gender_label_small: 'लिंग',
        state_conditions_label: 'राज्य की शर्तें',
        req_docs: 'आवश्यक दस्तावेज',
        how_to_apply: 'आवेदन कैसे करें (चरण-दर-चरण)',
        renewal_cond: 'नवीनीकरण की शर्तें',
        apply_portal_btn: 'अभी आवेदन करें / पोर्टल खोलें',

        // Start Working Tab Extended
        choose_category: 'एक श्रेणी चुनें',
        find_jobs_matching: 'अपनी योग्यता और रुचियों के अनुरूप नौकरियां खोजें',
        match_score_active: 'स्मार्ट मैच स्कोर सक्रिय है',
        match_score_desc: 'नौकरियाँ आपकी योग्यता और प्रोफ़ाइल के आधार पर रैंक की गई हैं।',
        jobs_count_suffix: ' नौकरियां',
        no_jobs_match: 'कोई नौकरी इस फ़िल्टर से मेल नहीं खाती।',
        eligibility_detail_label: 'पात्रता',
        required_skills_label: 'आवश्यक कौशल',
        where_to_apply_label: 'कहां आवेदन करें',
        monthly_salary_label: 'मासिक वेतन',
        exam_based_label: 'परीक्षा-आधारित',
        match_label: 'मैच',
        apply_now_btn: 'अभी आवेदन करें',

        // Skill Courses Tab Extended
        choose_skill_area: 'एक कौशल क्षेत्र चुनें',
        short_term_courses_desc: 'अल्पकालिक पाठ्यक्रम • प्रमाणन • नौकरी के लिए तैयार कौशल',
        recommended_for: 'आपके लिए अनुशंसित: ',
        courses_count_suffix: ' पाठ्यक्रम',
        no_courses_match: 'कोई भी पाठ्यक्रम इस फ़िल्टर से मेल नहीं खाता।',
        free_govt_training: 'मुफ्त सरकारी प्रशिक्षण',
        paid_private_training: 'सशुल्क निजी प्रशिक्षण',
        course_info_label: 'पाठ्यक्रम की जानकारी',
        duration_label_small: 'अवधि',
        authority_label: 'प्राधिकरण',
        mode_label: 'मोड',
        top_platforms_label: 'शीर्ष प्लेटफॉर्म / संस्थान',
        job_roles_label: 'नौकरी की भूमिकाएं',

        // Business Tab Extended
        explore_business_categories: 'व्यावसायिक श्रेणियों का अन्वेषण करें',
        find_perfect_business_desc: 'अपने कौशल और बजट के लिए सही व्यावसायिक विचार खोजें',
        why_start_business: 'व्यवसाय क्यों शुरू करें?',
        starting_small_business_desc: 'एक छोटा व्यवसाय शुरू करने से वित्तीय स्वतंत्रता, लचीलापन और असीमित विकास क्षमता मिलती है।',
        business_ideas_count_suffix: ' विचार',
        no_ideas_found: 'अभी तक इस श्रेणी के लिए कोई विचार नहीं मिला।',
        avg_profit_label: 'औसत लाभ: ',
        expected_profit_label: 'अपेक्षित लाभ',
        time_to_break_even: 'ब्रेक-ईवन का समय',
        financial_breakdown: 'वित्तीय विवरण',
        initial_setup_budget: 'प्रारंभिक सेटअप बजट: ',
        monthly_operating_cost: 'मासिक परिचालन लागत:',
        req_eligibility_label: 'आवश्यकताएं और पात्रता',
        manpower_needs_label: 'जनशक्ति की आवश्यकताएं:',
        marketing_scalability_label: 'विपणन और स्केलेबिलिटी',
        marketing_tips_label: 'विपणन युक्तियाँ:',
        scalability_potential_label: 'स्केलेबिलिटी क्षमता:',
        bonus_tips_resources: 'बोनस टिप्स और संसाधन',

        // Qualification Titles
        qual_10th: '10वीं',
        qual_12th: '12वीं',
        qual_diploma: 'डिप्लोमा',
        qual_iti: 'ITI',
        qual_grad: 'स्नातक (Graduation)',

        // New / Missing Strings
        leaving_careerpath: 'CareerPath छोड़ रहे हैं',
        leaving_careerpath_desc: 'आप एक बाहरी साइट खोलने वाले हैं। जारी रखें?',
        cannot_open_link: 'लिंक नहीं खोला जा सकता',
        link_unavailable: 'लिंक अनुपलब्ध है',
        link_unavailable_desc: 'कोई आधिकारिक लिंक उपलब्ध नहीं है या लिंक अमान्य है।',
        unable_to_open: 'लिंक खोलने में असमर्थ।',
        monthly_salary_suffix: '/माह',
        for_you_badge: '✦ आपके लिए',
        free_tag: 'मुफ़्त',
        online_mode: 'ऑनलाइन',
        offline_mode: 'ऑफलाइन',
        blended_mode: 'मिश्रित (Blended)',
        nsdc_pmkvy_desc: 'NSDC / PMKVY / DDU-GKY',
        placement_support: 'प्लेसमेंट सहायता',
        cert_on_completion: 'पूर्ण होने पर प्रमाणपत्र',
        rural_friendly_centres: 'ग्रामीण-अनुकूल केंद्र',
        industry_recognized_certs: 'उद्योग-मान्यता प्राप्त प्रमाणपत्र',
        live_projects_mentors: 'लाइव प्रोजेक्ट और मेंटर',
        higher_job_roi: 'उच्च जॉब आरओआई',
        global_platforms: 'वैश्विक प्लेटफॉर्म',
        budget_very_low: 'बहुत कम',
        budget_low: 'कम',
        budget_medium: 'मध्यम',
        budget_high: 'उच्च',
        example_success_tip: 'उदाहरण / सफलता की टिप:',
        starter_kit_rec: 'स्टार्टर किट की सिफारिश:',

        // Course Badges
        high_salary: 'उच्च वेतन',
        remote_friendly: 'रिमोट फ्रेंडली',
        future_skill: 'फ्यूचर स्किल',
        global_certification: 'वैश्विक प्रमाणन',
        govt_sponsored: 'सरकारी प्रायोजित',
        free_course: 'मुफ्त कोर्स',
        self_employment: 'स्व-रोजगार',
        industry_skill: 'उद्योग कौशल',
        field_job: 'फील्ड जॉब',
        freelancing_badge: 'फ्रीलांसिंग',
        stable_career: 'स्थिर करियर',
        corporate_jobs: 'कॉर्पोरेट नौकरियां',
        rural_support: 'ग्रामीण सहायता',
        work_from_home: 'घर से काम',
        no_degree_required: 'डिग्री की आवश्यकता नहीं',

        // Alerts & Common
        error: 'त्रुटि',
        success: 'सफलता',
        update_failed: 'अपडेट विफल',
        something_went_wrong: 'अपडेट करते समय कुछ गलत हो गया।',
        unable_find_session: 'यूजर सेशन खोजने में असमर्थ।',
        fill_mandatory_fields: 'कृपया अनिवार्य फ़ील्ड भरें (भूमिका, विवरण, मोबाइल)',
        failed_save_post: 'पोस्ट सहेजने में विफल',
        delete_btn: 'हटाएं',
        
        // Explore Filters & Subtitles
        filter_higher: 'उच्च शिक्षा',
        filter_salary: 'उच्च वेतन',
        filter_skill: 'कौशल-आधारित',
        filter_abroad: 'विदेश में पढ़ाई',
        filter_entry: 'प्रवेश-स्तर',
        qual_subtitle_10th: 'स्ट्रीम चुनाव, डिप्लोमा, ITI',
        qual_subtitle_12th: 'डिग्री, इंजीनियरिंग, मेडिकल',
        qual_subtitle_diploma: 'B.Tech प्रवेश, सरकारी नौकरियां',
        qual_subtitle_iti: 'तकनीकी भूमिकाएं, शिक्षुता (Apprenticeship)',
        qual_subtitle_grad: 'PG, UPSC, MBA, विशेष नौकरियां',

        // Explore Tags
        tag_govt_job: 'सरकारी नौकरी',
        tag_private_job: 'निजी नौकरी',
        tag_high_salary: 'उच्च वेतन',
        tag_higher_study: 'उच्च शिक्षा',
        tag_study_abroad: 'विदेश में पढ़ाई',
        tag_skill_based: 'कौशल-आधारित',
        tag_entrepreneurship: 'उद्यमिता',
    },
    mr: {
        // Auth
        welcome_roadmap: 'तुमचा करिअर रोडमॅप',
        auth_subtitle: 'तुमच्या आवडीनुसार मार्ग शोधा.',
        sign_in: 'साइन इन करा',
        sign_up: 'साइन अप करा',
        guest: 'पाहुणे म्हणून पुढे जा',
        email: 'ईमेल पत्ता',
        password: 'पासवर्ड',

        // Onboarding
        welcome: 'स्वागत आहे',
        onboarding_subtitle: 'तुमच्या भविष्यासाठी सर्वोत्तम मार्ग शोधूया',
        select_lang: 'तुमची भाषा निवडा',
        get_started: 'सुरू करा',
        choose_lang: 'भाषा निवडा',

        // Tabs Layout
        tab_home: 'होम',
        tab_explore: 'एक्सप्लोर',
        tab_plan: 'माझा प्लॅन',
        tab_freelance: 'फ्रीलांसिंग',
        tab_profile: 'प्रोफाईल',

        // Home Screen
        hello_student: 'नमस्कार, विद्यार्थी! 👋',
        home_subtitle: 'चला तुमचा करिअर रोडमॅप तयार करूया',
        explore_section: 'तुम्हाला काय पाहायला आवडेल?',
        further_edu: 'पुढील शिक्षण',
        further_edu_desc: 'शाखा, पदवी, महाविद्यालये',
        start_working: 'काम सुरू करा',
        start_working_desc: 'शासकीय आणि खाजगी नोकऱ्या',
        skill_courses: 'कौशल्य अभ्यासक्रम',
        skill_courses_desc: 'प्रमाणपत्रे, व्यवसाय',
        start_business: 'व्यवसाय सुरू करा',
        start_business_desc: 'कल्पना आणि फ्रीलांस',
        recommended: 'तुमच्यासाठी शिफारस केलेले',
        see_more: 'आणखी पहा',

        // Explore Screen
        explore_title: 'कॉलेज एक्सप्लोरर',
        explore_subtitle: 'तुमच्या पदवीसाठी सर्वोत्तम संस्था शोधा',
        search_placeholder: 'कॉलेज, पदव्या शोधा...',
        filter_all: 'सर्व',
        filter_govt: 'शासकीय',
        filter_private: 'खाजगी',
        tuition_fees: 'शिक्षण शुल्क',
        college_type: 'प्रकार',
        placement: 'प्लेसमेंट',
        save: 'सेव्ह',
        view_details: 'तपशील पहा',

        // Plan Screen
        plan_title: 'माझा करिअर प्लॅन',
        plan_subtitle: 'तुमची उद्दिष्टे आणि सेव्ह केलेल्या बाबींचा मागोवा घ्या',
        status_in_progress: 'प्रगतीपथावर',
        status_pending: 'प्रलंबित',
        status_completed: 'पूर्ण झाले',
        bookmarks_title: 'सेव्ह केलेले बुकमार्क',
        no_bookmarks: 'अद्याप कोणतेही बुकमार्क नाहीत. कॉलेज किंवा कोर्सेस शोधा आणि सेव्ह करा.',

        // Assist Screen
        assist_title: 'करिअर सहाय्यक',
        ask_anything: 'मला काहीही विचारा...',
        bot_initial_msg: 'नमस्कार! मी तुमचा करिअर सहाय्यक आहे. मी तुम्हाला आज कशी मदत करू शकतो?',
        bot_feedback_msg: 'हा एक उत्तम मार्ग वाटतो! तुम्हाला त्या क्षेत्रासाठी काही संबंधित कोर्सेस आणि कॉलेज शोधायला आवडेल का?',

        // Profile Screen
        profile_name: 'विद्यार्थी वापरकर्ता',
        profile_sub: '12 वी उत्तीर्ण • विज्ञान शाखा',
        retake_assessment: 'पुन्हा मूल्यांकन करा',
        edit_info: 'वैयक्तिक माहिती संपादित करा',
        app_settings: 'अ‍ॅप सेटिंग्ज',
        privacy_terms: 'गोपनीयता आणि अटी',
        contact_support: 'सपोर्टशी संपर्क साधा',
        log_out: 'लॉग आउट',
        logout_confirm: 'तुम्हाला नक्की लॉग आउट करायचे आहे का?',
        retake_confirm: 'यामुळे तुमचे करिअर मूल्यांकन पुन्हा सुरू होईल. पुढे जावे?',
        cancel: 'रद्द करा',
        continue: 'पुढे जा',

        // Scholarship Card
        scholarship_title: 'आठवड्याची शिष्यवृत्ती 🎯',
        scholarship_name: 'राज्य गुणवत्ता शिष्यवृत्ती',
        scholarship_desc: '८०%+ गुण मिळवणाऱ्या १२ वी उत्तीर्ण विद्यार्थ्यांसाठी',
        scholarship_grant: '₹२५,००० पर्यंत अनुदान',
        scholarship_deadline: 'यापूर्वी अर्ज करा: १५ मार्च',
        apply_now: 'आता अर्ज करा',

        // Resume Card
        resume_instant_title: 'तुमचा रिझ्युमे त्वरित तयार करा 🧾',
        resume_instant_desc: 'फक्त ५ प्रश्नांची उत्तरे द्या आणि PDF रिझ्युमे मिळवा! इंटर्नशिप आणि एंट्री-लेवल नोकरीसाठी योग्य.',
        build_resume: 'रिझ्युमे तयार करा',

        // Freelancing Hub
        freelance_hub: 'फ्रीलांसिंग हब',
        freelance_sub: 'प्रोजेक्ट्स शोधा किंवा तुमचे कौशल्य दाखवा',
        browse_posts: 'पोस्ट ब्राउझ करा',
        create_post_tab: 'पोस्ट तयार करा',
        edit_post_tab: 'पोस्ट संपादित करा',
        role_label: 'तुमची व्यावसायिक भूमिका काय आहे?',
        role_placeholder: 'उदा. ग्राफिक डिझाइनर, फ्रीलांस लेखक',
        desc_label: 'आम्हाला तुमच्या सेवा आणि अनुभवाबद्दल सांगा',
        desc_placeholder: 'तुम्ही क्लायंटसाठी काय करू शकता याचे वर्णन करा...',
        skills_label: 'कौशल्ये (कॉमाने वेगळे करा)',
        skills_placeholder: 'उदा. लोगो डिझाइन, फोटोशॉप, कॉपीरायटींग',
        mobile_label: 'मोबाईल नंबर *',
        mobile_placeholder: 'उदा. 9876543210',
        linkedin_label: 'लिंक्डइन प्रोफाइल URL',
        linkedin_placeholder: 'https://linkedin.com/in/yourname',
        publish_post: 'पोस्ट प्रकाशित करा',
        update_post: 'पोस्ट अपडेट करा',
        cancel_edit: 'संपादन रद्द करा',
        call_now: 'आता कॉल करा',
        delete_post_title: 'पोस्ट हटवा',
        delete_post_confirm: 'तुम्हाला नक्की ही पोस्ट हटवायची आहे का?',
        post_success: 'तुमची पोस्ट प्रकाशित झाली आहे!',
        update_success: 'पोस्ट यशस्वीरित्या अपडेट झाली!',
        no_posts: 'अद्याप कोणतीही पोस्ट नाही. पहिली पोस्ट करणारे व्हा!',

        // Resume Builder
        resume_builder_title: 'रिझ्युमे बिल्डर',
        personal_info: 'वैयक्तिक माहिती',
        edu_info: 'शिक्षण',
        exp_info: 'अनुभव / प्रकल्प',
        skills_info: 'कौशल्ये',
        full_name_ph: 'पूर्ण नाव',
        email_ph: 'ईमेल पत्ता',
        phone_ph: 'फोन नंबर',
        location_ph: 'ठिकाण (शहर, राज्य)',
        summary_ph: 'व्यावसायिक सारांश',
        add_skill: 'कौशल्य जोडा',
        skill_name_ph: 'कौशल्याचे नाव',
        add_edu: 'शिक्षण जोडा',
        edu_count: 'शिक्षण #',
        school_ph: 'शाळा/कॉलेजचे नाव',
        degree_ph: 'पदवी/कोर्स (उदा. बी.टेक कॉम्प्युटर सायन्स)',
        year_ph: 'वर्ष (उदा. 2020 - 2024)',
        add_exp: 'अनुभव जोडा',
        item_count: 'एटम #',
        company_ph: 'कंपनी/प्रकल्पाचे नाव',
        role_ph: 'भूमिका (उदा. सॉफ्टवेअर इंजिनिअर इंटर्न)',
        duration_ph: 'कालावधी (उदा. जून २०२३ - वर्तमान)',
        desc_ph: 'वर्णन (पर्यायी)',
        select_tpl_preview: 'टेम्पलेट निवडा आणि प्रीव्ह्यू पहा',
        generate_pdf: 'पीडीएफ तयार करा',
        edit_tab: 'संपादन करा',
        templates_tab: 'टेम्पलेट्स',
        preview_tab: 'प्रीव्ह्यू',

        // Profile Extended
        profile_overview: 'आढावा',
        profile_interests: 'आवड',
        profile_settings: 'सेटिंग्ज',
        edit_profile_title: 'प्रोफाइल संपादित करा',
        not_set: 'सेट केलेले नाही',
        marks_label: 'गुण: ',
        marks_not_set: 'गुण नमूद केलेले नाहीत',
        no_interests: 'कोणतीही आवड निवडली नाही',
        full_name_label: 'पूर्ण नाव',
        location_label: 'ठिकाण',
        qual_label: 'पात्रता',
        stream_label: 'शाखा',
        marks_cgpa_label: 'गुण / CGPA',
        saving: 'जतन करत आहे...',
        save_changes: 'बदल जतन करा',
        profile_update_success: 'प्रोफाइल यशस्वीरित्या अपडेट झाली.',

        // Explore Extended
        after_label: 'नंतर ',
        select_qual: 'तुमची पात्रता निवडा',
        select_qual_desc: 'तुम्हाला सर्वात संबंधित शैक्षणिक मार्ग दाखवण्यासाठी',
        options_suffix: ' पर्याय',
        goal_label: 'तुमचे ध्येय काय आहे?',
        no_options: 'या फिल्टरसाठी कोणतेही पर्याय सापडले नाहीत.',
        duration_label: 'कालावधी:',
        eligibility_label: 'पात्रता:',
        govt_jobs_label: '🏛️ शासकीय नोकऱ्या / पर्याय:',
        private_sector_label: '💼 खाजगी क्षेत्रातील भूमिका:',
        higher_study_label: '🎓 उच्च शिक्षण मार्ग:',
        branches_coming_soon: 'या मार्गासाठी तपशीलवार शाखा लवकरच येत आहेत!',
        coming_soon_title: 'लवकरच येत आहे',

        // Scholarship Screen Extended
        scholarships_header: 'शिष्यवृत्ती',
        available_count: ' शिष्यवृत्ती उपलब्ध आहेत',
        search_scholarships_ph: 'शिष्यवृत्ती, टॅग, प्रकार शोधा...',
        filter_title: 'शिष्यवृत्ती फिल्टर करा',
        edu_level_label: 'शिक्षण पातळी',
        scholarship_type_label: 'शिष्यवृत्तीचा प्रकार',
        special_cat_label: 'विशेष प्रवर्ग',
        reset_btn: 'रीसेट करा',
        apply_filters_btn: 'फिल्टर लागू करा',
        found_count: ' शिष्यवृत्ती सापडल्या',
        clear_filters: 'फिल्टर पुसून टाका',
        no_scholarships_found: 'कोणतीही शिष्यवृत्ती सापडली नाही',
        try_adjust_filters: 'तुमचा शोध किंवा फिल्टर बदलून पहा',
        load_more: 'आणखी पहा',
        end_list: 'तुम्ही सूचीच्या शेवटी पोहोचला आहात',
        benefit_label: 'रक्कम / लाभ',
        eligibility_criteria: 'पात्रता निकष',
        qual_label_small: 'पात्रत्ता',
        min_percentage_label: 'किमान टक्केवारी',
        family_income_label: 'कौटुंबिक उत्पन्न मर्यादा',
        category_label_small: 'प्रवर्ग',
        gender_label_small: 'लिंग',
        state_conditions_label: 'राज्य अटी',
        req_docs: 'आवश्यक कागदपत्रे',
        how_to_apply: 'अर्ज कसा करावा (टप्प्याटप्प्याने)',
        renewal_cond: 'नूतनीकरण अटी',
        apply_portal_btn: 'आता अर्ज करा / पोर्टल उघडा',

        // Start Working Tab Extended
        choose_category: 'एक श्रेणी निवडा',
        find_jobs_matching: 'तुमच्या पात्रता आणि आवडीनुसार नोकऱ्या शोधा',
        match_score_active: 'स्मार्ट मॅच स्कोअर सक्रिय आहे',
        match_score_desc: 'नोकऱ्या तुमच्या पात्रतेच्या आणि प्रोफाइलच्या आधारे रँक केल्या आहेत.',
        jobs_count_suffix: ' नोकऱ्या',
        no_jobs_match: 'या फिल्टरशी जुळणारी कोणतीही नोकरी नाही.',
        eligibility_detail_label: 'पात्रता',
        required_skills_label: 'आवश्यक कौशल्ये',
        where_to_apply_label: 'कोठे अर्ज करावा',
        monthly_salary_label: 'मासिक पगार',
        exam_based_label: 'परीक्षा-आधारित',
        match_label: 'मॅच',
        apply_now_btn: 'आता अर्ज करा',

        // Skill Courses Tab Extended
        choose_skill_area: 'एक कौशल क्षेत्र निवडा',
        short_term_courses_desc: 'अल्पकालीन कोर्सेस • प्रमाणपत्रे • नोकरीसाठी कौशल्ये',
        recommended_for: 'तुमच्यासाठी शिफारस केलेले: ',
        courses_count_suffix: ' कोर्सेस',
        no_courses_match: 'या फिल्टरशी जुळणारा कोणताही कोर्स नाही.',
        free_govt_training: 'मोफत सरकारी प्रशिक्षण',
        paid_private_training: 'सशुल्क खाजगी प्रशिक्षण',
        course_info_label: 'कोर्सची माहिती',
        duration_label_small: 'कालावधी',
        authority_label: 'प्राधिकरण',
        mode_label: 'मोड',
        top_platforms_label: 'शीर्ष प्लॅटफॉर्म / संस्था',
        job_roles_label: 'नोकरीच्या भूमिका',

        // Business Tab Extended
        explore_business_categories: 'व्यावसायिक श्रेणी शोधा',
        find_perfect_business_desc: 'तुमच्या कौशल्यांसाठी आणि बजेटसाठी परिपूर्ण व्यवसाय कल्पना शोधा',
        why_start_business: 'व्यवसाय का सुरू करावा?',
        starting_small_business_desc: 'छोटा व्यवसाय सुरू केल्याने आर्थिक स्वातंत्र्य, लवचिकता आणि अमर्याद वाढीची क्षमता मिळते.',
        business_ideas_count_suffix: ' कल्पना',
        no_ideas_found: 'या श्रेणीसाठी अद्याप कोणतीही कल्पना सापडली नाही.',
        avg_profit_label: 'सरासरी नफा: ',
        expected_profit_label: 'अपेक्षित नफा',
        time_to_break_even: 'ब्रेक-ईव्हन वेळ',
        financial_breakdown: 'वित्तीय तपशील',
        initial_setup_budget: 'प्रारंभिक सेटअप बजेट: ',
        monthly_operating_cost: 'मासिक ऑपरेटिंग खर्च:',
        req_eligibility_label: 'आवश्यकता आणि पात्रता',
        manpower_needs_label: 'मनुष्यबळाची गरज:',
        marketing_scalability_label: 'मार्केटिंग आणि स्केलेबिलिटी',
        marketing_tips_label: 'मार्केटिंग टिप्स:',
        scalability_potential_label: 'वाढीची क्षमता:',
        bonus_tips_resources: 'बोनस टिप्स आणि संसाधने',

        // Qualification Titles
        qual_10th: '१० वी',
        qual_12th: '१२ वी',
        qual_diploma: 'डिप्लोमा',
        qual_iti: 'ITI',
        qual_grad: 'पदवी (Graduation)',

        // New / Missing Strings
        leaving_careerpath: 'CareerPath सोडत आहे',
        leaving_careerpath_desc: 'तुम्ही बाह्य साइट उघडणार आहात. पुढे जायचे?',
        cannot_open_link: 'लिंक उघडता येत नाही',
        link_unavailable: 'लिंक उपलब्ध नाही',
        link_unavailable_desc: 'कोणतीही अधिकृत लिंक उपलब्ध नाही किंवा लिंक अवैध आहे.',
        unable_to_open: 'लिंक उघडण्यात अक्षम.',
        monthly_salary_suffix: '/महिना',
        for_you_badge: '✦ तुमच्यासाठी',
        free_tag: 'मोफत',
        online_mode: 'ऑनलाइन',
        offline_mode: 'ऑफलाईन',
        blended_mode: 'मिश्रित (Blended)',
        nsdc_pmkvy_desc: 'NSDC / PMKVY / DDU-GKY',
        placement_support: 'प्लेसमेंट सहाय्य',
        cert_on_completion: 'पूर्ण झाल्यावर प्रमाणपत्र',
        rural_friendly_centres: 'ग्रामीण-अनुकूल केंद्रे',
        industry_recognized_certs: 'उद्योग-मान्यताप्राप्त प्रमाणपत्रे',
        live_projects_mentors: 'थेट प्रकल्प आणि मार्गदर्शक',
        higher_job_roi: 'उच्च जॉब आरओआय',
        global_platforms: 'जागतिक प्लॅटफॉर्म',
        budget_very_low: 'अत्यंत कमी',
        budget_low: 'कमी',
        budget_medium: 'मध्यम',
        budget_high: 'उच्च',
        example_success_tip: 'उदाहरण / यशाची टीप:',
        starter_kit_rec: 'स्टार्टर किट शिफारस:',

        // Course Badges
        high_salary: 'उच्च पगार',
        remote_friendly: 'रिमोट फ्रेंडली',
        future_skill: 'फ्यूचर स्किल',
        global_certification: 'जागतिक प्रमाणन',
        govt_sponsored: 'सरकारी प्रायोजित',
        free_course: 'मोफत कोर्स',
        self_employment: 'स्व-रोजगार',
        industry_skill: 'उद्योग कौशल्य',
        field_job: 'फील्ड जॉब',
        freelancing_badge: 'फ्रीलांसिंग',
        stable_career: 'स्थिर करिअर',
        corporate_jobs: 'कॉर्पोरेट नोकऱ्या',
        rural_support: 'ग्रामीण सहाय्य',
        work_from_home: 'घरातून काम',
        no_degree_required: 'पदवीची गरज नाही',

        // Alerts & Common
        error: 'त्रुटी',
        success: 'यश',
        update_failed: 'अपडेट अयशस्वी',
        something_went_wrong: 'अपडेट करताना काहीतरी चूक झाली.',
        unable_find_session: 'वापरकर्ता सत्र सापडले नाही.',
        fill_mandatory_fields: 'कृपया अनिवार्य फील्ड भरा (भूमिका, वर्णन, मोबाईल)',
        failed_save_post: 'पोस्ट जतन करण्यात अयशस्वी',
        delete_btn: 'हटवा',
        
        // Explore Filters & Subtitles
        filter_higher: 'उच्च शिक्षण',
        filter_salary: 'उच्च पगार',
        filter_skill: 'कौशल्य-आधारित',
        filter_abroad: 'परदेशात शिक्षण',
        filter_entry: 'प्रवेश-स्तर',
        qual_subtitle_10th: 'शाखा निवड, डिप्लोमा, ITI',
        qual_subtitle_12th: 'पदवी, अभियांत्रिकी, वैद्यकीय',
        qual_subtitle_diploma: 'B.Tech प्रवेश, शासकीय नोकऱ्या',
        qual_subtitle_iti: 'तांत्रिक भूमिका, प्रशिक्षण (Apprenticeship)',
        qual_subtitle_grad: 'PG, UPSC, MBA, विशेष नोकऱ्या',

        // Explore Tags
        tag_govt_job: 'शासकीय नोकरी',
        tag_private_job: 'खाजगी नोकरी',
        tag_high_salary: 'उच्च पगार',
        tag_higher_study: 'उच्च शिक्षण',
        tag_study_abroad: 'परदेशात शिक्षण',
        tag_skill_based: 'कौशल्य-आधारित',
        tag_entrepreneurship: 'उद्योजकता',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<LanguageId>('en');

    useEffect(() => {
        loadLanguage();
    }, []);

    const loadLanguage = async () => {
        const savedLang = await AsyncStorage.getItem('userLanguage');
        if (savedLang && (savedLang === 'en' || savedLang === 'hi' || savedLang === 'mr')) {
            setLanguageState(savedLang as LanguageId);
        }
    };

    const setLanguage = async (lang: LanguageId) => {
        setLanguageState(lang);
        await AsyncStorage.setItem('userLanguage', lang);
    };

    const t = (key: string) => {
        return (LANGUAGES[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
